### ISSUE TITLE
Control Panel: Added ability to change product options values ISSUES

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#109]
Issue 1: when edit/add option the price modifier ignored
-----------------------------------------------------------------------------------
![options-issue1](https://cloud.githubusercontent.com/assets/2631910/6729068/73763ab6-ce61-11e4-99f9-42cf1f818922.png)

Issue 2: if file type required do not allow adding with empty value
-----------------------------------------------------------------------------------
![options-issue2](https://cloud.githubusercontent.com/assets/2631910/6729069/73778f10-ce61-11e4-8bc2-f3754a2270d3.png)

Issue 3:
-----------------------------------------------------------------------------------
![options-issue3](https://cloud.githubusercontent.com/assets/2631910/6729070/737983e2-ce61-11e4-9045-4446d62491c7.png)

Issue 4: textarea doesnot support newline
-----------------------------------------------------------------------------------
![options-issue4](https://cloud.githubusercontent.com/assets/2631910/6729071/737f002e-ce61-11e4-8885-902951ef1c80.png)

Issue 5: checkbox type value (if added) not visible in admin and storefront
-----------------------------------------------------------------------------------
![options-issue5](https://cloud.githubusercontent.com/assets/2631910/6729075/73bcbe64-ce61-11e4-9e6d-f7ca13c07d8b.png)

Issue 6: Checkboxgroup option type ignore default value and looks not aligned in admin order edit
-----------------------------------------------------------------------------------
![options-issue6](https://cloud.githubusercontent.com/assets/2631910/6729073/73b7e18c-ce61-11e4-8e71-c841264c9fec.png)

Issue 7: please hide Hidden option type in storefront
-----------------------------------------------------------------------------------
![options-issue7](https://cloud.githubusercontent.com/assets/2631910/6729072/73b6192e-ce61-11e4-8b05-b13699752026.png)

Issue 8: required mark looks broken for some option types see screen
-----------------------------------------------------------------------------------
![options-issue8](https://cloud.githubusercontent.com/assets/2631910/6729074/73b99fae-ce61-11e4-9d7e-3a5a8e8ae04d.png)

Issue 9: when ADD product with Input option type - default value not visible
-----------------------------------------------------------------------------------
![options-issue9](https://cloud.githubusercontent.com/assets/2631910/6729076/73befda0-ce61-11e4-86f5-0fa4dd9ca75a.png)

Issue 10: when EDIT ordered product with Radio and Checkbox option types incorrect values shown in the popup
-----------------------------------------------------------------------------------
![options-issue10](https://cloud.githubusercontent.com/assets/2631910/6729077/73c13750-ce61-11e4-9e1b-2a42cd825cf2.png)

**Comment by abolabo** [comment]
issue 2: any required fields no more
 issue 7: can not to replicate. No any hidden option on SF
other fixed

**Comment by BasaraABC** [comment]
Issue A: hidden value visible for customer in order confirmation email
---------------------------------------------------------------------------------------------------
![issue1-hidden](https://cloud.githubusercontent.com/assets/2631910/6747783/95683b7e-cf10-11e4-8330-48b7996fcda1.png)

Issue B: not defined text
---------------------------------------------------------------------------------------
![issue2-notdefined](https://cloud.githubusercontent.com/assets/2631910/6747784/95cac410-cf10-11e4-9f39-14d1fa03a96b.png)

Issue C: still issues with price modifier - it work incorrectly please fix all cases (select option value with modifier, with negative modifier, without modifier)
---------------------------------------------------------------------------------------
![issue3-badfixed](https://cloud.githubusercontent.com/assets/2631910/6747785/95ccd930-cf10-11e4-8c7a-2102e6d472b7.png)

Issue D: not fixed issue with checkbox value
---------------------------------------------------------------------------------------
![issue4-badfixed](https://cloud.githubusercontent.com/assets/2631910/6747786/95cdeef6-cf10-11e4-872e-764ff9dd35c7.png)

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
<strong>Abolabo</strong>, the price modifier issue is still not work correctly please spend a bit more time for test when fixing.(Make sure all option types with/without price modifier fixed)
Also issue with Checkbox value visibility is NOT FIXED.
 See screenshots attached for price modifier bug
![options](https://cloud.githubusercontent.com/assets/2631910/6775389/1333d97e-d163-11e4-99e8-c3fae5d132c9.png)
--------------------------------------------------------------------------------------------
--------------------------------------------------------------------------------------------
![options2](https://cloud.githubusercontent.com/assets/2631910/6775435/b253c398-d163-11e4-9f7f-787f60f9415e.png)

**Comment by abolabo** [comment]
bug  with selectbox fixed. 
About checkbox. I think we can left as-is because we allow to change unit price manually, and also few options can affect it (in case when few options have price modifier). Let merchant decides on his own.

**Comment by BasaraABC** [comment]
Hi.
1. Selectbox issue is again not fixed  see new screenshot
2. We can not left issue with checkbox. Please do not force merchant to use calculator and make mistakes (зачем вьідумьівать велосипед - нужно повторить функционал сторефронта).  <em>We already receive respond from our user who install abc 1.2.2 and mark this problem as BUG. </em> <strong>Kindly ask You - Please fix all option types. I will qa all of them</strong>
3. About checkbox value visibility issue - issue not fixed fully. Checkbox value is Not visible in the customer order history (rt=account/invoice), cart page (rt=checkout/cart), checkout summary page (rt=checkout/confirm).

![options-again-not-fixd](https://cloud.githubusercontent.com/assets/2631910/6819284/4395316e-d2f1-11e4-8580-45676fa6e168.png)

**Comment by abolabo** [comment]
Now admin can not to edit unit prices + Options works as in SF

**Comment by BasaraABC** [comment]
Hi. issues # 1 and # 3 from previous post are not fixed. Please fix both.
See new more clear screenshot for issue#1 (with default value with price modifier )
![options](https://cloud.githubusercontent.com/assets/2631910/6847527/f8b4c4ac-d3f9-11e4-8da0-40201093a8c3.png)

**Comment by abolabo** [comment]
fixed

**Comment by abantecart** [comment]
Great. Thank you
