### ISSUE TITLE
warning in the log 

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#124]
When RL window opened warning in the log see screen (note: image resource have filled name, title, description)
![rl-warning](https://cloud.githubusercontent.com/assets/2631910/7452717/6c10b3ca-f28b-11e4-9b63-78cb3dec5c01.png)

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Issue not  fixed. Still visible in latest 122
2015-05-11 3:10:44 - warning: AbanteCart core v.1.2.2 Invalid argument supplied for foreach() in <b>/......./htdocs/abc122_m05d08/core/lib/resource_manager.php</b> on line <b>660</b>

**Comment by BasaraABC** [comment]
Issue still visible in latest 122
2015-05-11 3:12:59 - warning: AbanteCart core v.1.2.2 Invalid argument supplied for foreach() in <b>/../htdocs/abc122_m05d11/core/lib/resource_manager.php</b> on line <b>660</b>
