### ISSUE TITLE
RL linked to incorrect

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#125]
RL show incorrect 'Linked to' information
----------------
![rlbug](https://cloud.githubusercontent.com/assets/2631910/7471222/961d6334-f34e-11e4-8616-c6118fa76d0e.png)

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Did you forgot to upload your latest fixes? I did not see fix in latest 122 install

**Comment by abolabo** [comment]
yes. sorry. all local fixed now pushed
