### ISSUE TITLE
dev: incorrect availability on product page

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1253]
The total available stock displayed on product page is incorrect see conditions
<img width="790" alt="2in" src="https://user-images.githubusercontent.com/2631910/55875744-0fe49d80-5bc0-11e9-90d9-a66f758e44a4.png">

**Comment by abolabo** [comment]
fixed by previous commits

**Comment by BasaraABC** [comment]
Issue is not fixed. 
![four](https://user-images.githubusercontent.com/2631910/55932887-a2834c00-5c55-11e9-8e16-9c999102df90.png)

**Comment by BasaraABC** [comment]
I think +1 problem affected issue #1251

**Comment by abolabo** [comment]
cannot to replicate. need more details

**Comment by abantecart** [comment]
@abantecart I think @BasaraABC provided enough details. 
The actual value should be 2 + 3 = 5. This should be accumulative or just show "In stock" in case of options.

**Comment by BasaraABC** [comment]
The "Green" option value set Track stock OFF so we should accumulate as "3 in stock" or just "in stock"

**Comment by abantecart** [comment]
@abolabo Spent a bit more effort to investigate
The issue is here:
$total_quantity = $this->model_catalog_product->hasAnyStock($product_id);

**Comment by abolabo** [comment]
If one of options value have stock tracking OFF and another ON we cannot to calculate common quantity 

![image](https://user-images.githubusercontent.com/1264239/56018717-8641e680-5d0b-11e9-99cb-b958fe2d73ed.png)

![image](https://user-images.githubusercontent.com/1264239/56018728-92c63f00-5d0b-11e9-925e-731890245260.png)

**Comment by BasaraABC** [comment]
@abolabo please set Option to be Required.

**Comment by BasaraABC** [comment]
See screenshot from my side
![stock222](https://user-images.githubusercontent.com/2631910/56019363-95865b80-5d2e-11e9-881d-b77e65cf843b.png)
