### ISSUE TITLE
Order detail changes - currency handling on different browsers

### ISSUE THREAD

**Issue by goatlady102** [abantecart/abantecart-src#1309]
I need some assistance here - have been unsuccessful in figuring out how to fix this.  Admin changes to order-detail  in a Chrome browser results in the sub-totals (not the products)  being reverted to the cart default currency setting.  Resulting in a mixed currency in the order detail.
Firefox -  leaves the original currency thru the complete order.  

Here's the steps to replicate :
Clean v 1.2.15 install using Softaculous, only default demo install including COD, Flat rate shipping and the three currencies in the demo.   No modifications made to original demo install.
Cart default currency  USD
Running PHP 7.2 and 10.3.20-MariaDB 
FireFox Browser 70.0.1 (64-bit)
The Test   - 
Make an order –in Pound Sterling 
Order is correct
![image](https://user-images.githubusercontent.com/7943102/68723084-2a7b5c80-057d-11ea-98cd-933af01ad9be.png)

In admin still on Firefox Browser - open order to make a modification
Change qty of the one product from 1 to 2
Use Save and Recalculate so taxes update also  Pounds Sterling remain as they should

![image](https://user-images.githubusercontent.com/7943102/68723102-36671e80-057d-11ea-91c0-dee574c9e187.png)

Next added a product  and used Save and recalculate   still all correct.

![image](https://user-images.githubusercontent.com/7943102/68723119-4252e080-057d-11ea-97f6-a6ff15d7cea4.png)

Now going to a Chrome browser Version 78.0.3904.97 (Official Build) (64-bit) log into same admin panel
Go to the order detail of the SAME order placed previously all amounts are still showing Pounds Sterling

Change qty on an item and use Save and Recalculate - now sub-total , shipping, taxes and Total are converted to USD   
![image](https://user-images.githubusercontent.com/7943102/68723134-50a0fc80-057d-11ea-8373-d73d404b4fd9.png)

Thanks for looking at this,
Le

**Comment by BasaraABC** [comment]
It is bug. Thank you for report

**Comment by goatlady102** [comment]
Any idea when you might get a fix for this one?  It's a bit of an issue for sites using multiple currencies.
Thanks

**Comment by BasaraABC** [comment]
Dev team will fix in in next release. No ETA yet

**Comment by abantecart** [comment]
@BasaraABC This issue is fixed. Please review

**Comment by vdvpie22** [comment]
@abantecart Separate recalculation is buggy

**Comment by abantecart** [comment]
@BasaraABC I committed one more fix that should resolve all issues related to SF currency conflict

**Comment by BasaraABC** [comment]
Still issue with adding new products to the order. If the storefront session is POUND then incorrect currency when adding new products
![pound](https://user-images.githubusercontent.com/2631910/78672242-97b3d380-790a-11ea-8c39-4902fd60d422.jpg)

**Comment by BasaraABC** [comment]
Issue is not fixed. How to replicate. 
1. Place order in £
2. switch storefront currency to €
3. in admin open order (£ order)
4. try to add new product. In modal product price will switch to euro
<img width="879" alt="uero" src="https://user-images.githubusercontent.com/2631910/79737339-6208e480-8325-11ea-844d-c17edd165cf6.png">
