### ISSUE TITLE
realex payment

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1320]
For any card number regular or 3dsecure and date same error "does not conform to the schema"
<img width="592" alt="realex" src="https://user-images.githubusercontent.com/2631910/77752768-c6a08e80-705a-11ea-80b6-69920c9d981e.png">

**Comment by abolabo** [comment]
fixed but i got another error related to suporting of USD currency. Probably related to test account on realex side.

**Comment by BasaraABC** [comment]
Initial issue visible in the fast checkout. Please fix
<img width="759" alt="2020-05-08_16-43-12" src="https://user-images.githubusercontent.com/2631910/81393736-0c1ca500-914b-11ea-8335-b9a816fd39b0.png">

**Comment by BasaraABC** [comment]
Issue is not fixed. php 7.4.4
In test I use this card number 4263971921001307
<img width="788" alt="realex" src="https://user-images.githubusercontent.com/2631910/81531419-e4b51a80-938c-11ea-959b-8e64f0eae192.png">
