### ISSUE TITLE
fast checkout not work when Guest is OFF

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#1459]
Fast checkout is not working if Guest Checkout is OFF (config_guest_checkout)
![fc](https://user-images.githubusercontent.com/2631910/112946170-66599680-915f-11eb-8543-e66f676eb822.png)

**Comment by abolabo** [comment]
already fixed in 1.3.0

**Comment by BasaraABC** [comment]
Please check again. It is not fixed
<img width="886" alt="2021-04-02_13-05-23" src="https://user-images.githubusercontent.com/2631910/113386380-58508380-93b4-11eb-8069-52e1b060b933.png">
