### ISSUE TITLE
embed SF:  links in firefox and chrome

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#168]
<img width="808" alt="embed-issue11" src="https://cloud.githubusercontent.com/assets/2631910/8569857/e31dabd8-25a5-11e5-97ba-227129bd4f80.png">

**Comment by abantecart** [comment]
Fixed.

**Comment by BasaraABC** [comment]
Issue not fixed for me. Same problem with latest install (15/07/2015)

**Comment by abantecart** [comment]
Fixed. Please reinstall, clear cache and retest.
