### ISSUE TITLE
miised image - last installation step

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#239]
<img width="786" alt="abantecart_-_installation" src="https://cloud.githubusercontent.com/assets/2631910/9574399/bc2b6ebe-4ff0-11e5-8883-992c3e13e650.png">

**Comment by abantecart** [comment]
Fixed

**Comment by BasaraABC** [comment]
issue not fixed. Still visible

**Comment by abantecart** [comment]
Fixed

**Comment by BasaraABC** [comment]
still broken in fresh install
"NetworkError: 404 Not Found - http://dev06.********/image/conrib_btn_sm.png"

**Comment by abantecart** [comment]
What is going on

**Comment by abantecart** [comment]
Copied image to install directory to make it easier.
