### ISSUE TITLE
admin login

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#283]
there is an issue with admin login. 
http://forum.abantecart.com/index.php/topic,4130.msg17902.html#msg17902

I can not replicate it in major browsers but it were replicated in [Citrio chrome based browser](http://citrio.com/windows) with bitnami localhost installation. Every time I start this browser I need to clear browser cache to able login in admin

#### In the AbanteCart error log I have:
2015-10-26 21:48:50 - warning: AbanteCart core v.1.2.4 session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in <b>/ abantecart/htdocs/core/lib/session.php</b> on line <b>86</b>
2015-10-26 21:48:50 - warning: AbanteCart core v.1.2.4 Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in <b>Unknown</b> on line <b>42</b>
2015-10-26 21:48:50 - warning: AbanteCart core v.1.2.4 Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/php/tmp) in <b>Unknown</b> on line <b>42</b>
2015-10-26 21:48:50 - warning: AbanteCart core v.1.2.4 session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in <b>/ abantecart/htdocs/core/lib/session.php</b> on line <b>86</b>
2015-10-26 21:48:50 - warning: AbanteCart core v.1.2.4 session_start(): Cannot start session with empty session ID in <b>/ abantecart/htdocs/core/lib/session.php</b> on line <b>101</b>
2015-10-26 21:48:50 - warning: AbanteCart core v.1.2.4 session_destroy(): Session object destruction failed in <b>/ abantecart/htdocs/core/lib/session.php</b> on line <b>103</b>

**Comment by abantecart** [comment]
This is fixed.

**Comment by BasaraABC** [comment]
Still get new warnings after browser restart 
2015-10-28 2:38:05 - warning: AbanteCart core v.1.2.5 session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in <b>/apps/abantecart/htdocs/core/lib/session.php</b> on line <b>89</b>
2015-10-28 2:38:05 - warning: AbanteCart core v.1.2.5 Unknown: The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in <b>Unknown</b> on line <b>42</b>
2015-10-28 2:38:05 - warning: AbanteCart core v.1.2.5 Unknown: Failed to write session data (files). Please verify that the current setting of session.save_path is correct (/php/tmp) in <b>Unknown</b> on line <b>42</b>
2015-10-28 2:38:05 - warning: AbanteCart core v.1.2.5 session_start(): The session id is too long or contains illegal characters, valid characters are a-z, A-Z, 0-9 and '-,' in <b>/apps/abantecart/htdocs/core/lib/session.php</b> on line <b>89</b>
2015-10-28 2:38:05 - warning: AbanteCart core v.1.2.5 session_start(): Cannot start session with empty session ID in <b>/apps/abantecart/htdocs/core/lib/session.php</b> on line <b>111</b>
2015-10-28 2:38:05 - warning: AbanteCart core v.1.2.5 session_destroy(): Session object destruction failed in <b>/apps/abantecart/htdocs/core/lib/session.php</b> on line <b>113</b>

**Comment by abantecart** [comment]
Let's try to debug it. I can not install Citrio. It is only for windows

**Comment by BasaraABC** [comment]
Citrio installer for Mac http://citrio.com/mac

**Comment by abantecart** [comment]
Installed. I do not get this issue. 
I get "Ads block is enabled in your browser", but I think this is normal
