### ISSUE TITLE
incorrect text in Customer's Grid

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#290]
Should be 'Customer details'
<img width="1086" alt="customers" src="https://cloud.githubusercontent.com/assets/2631910/10818839/13cf2bf6-7e77-11e5-9d2e-ad65ade29919.png">

**Comment by abantecart** [comment]
Same happens on order grid.

**Comment by abolabo** [comment]
hmm..in orders grid i see text "Details"

**Comment by abolabo** [comment]
fixed

**Comment by abantecart** [comment]
The root of the problem was not fixed. We had a bug in core language construct. Fixed. Now

We need to test and pay attention to languages.

**Comment by BasaraABC** [comment]
I notice problems on product page. All buttons texts are missed 
<img width="748" alt="lancome_hypnose_doll_lashes_mascara_4-piece_gift_set" src="https://cloud.githubusercontent.com/assets/2631910/10998385/5a54acda-84c7-11e5-8aa3-9a27a89ffabe.png">

**Comment by abantecart** [comment]
I am looking. This is related to last language change

**Comment by abantecart** [comment]
Fixed
