### ISSUE TITLE
disable html rendering in editor

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#326]
In banner HTML (source) editor, if you put `<li>...</li> after save <ul>` is added. Disable all HTML rendering in editor.

<img width="621" alt="banner-edit" src="https://cloud.githubusercontent.com/assets/2631910/12257752/a860890a-b93b-11e5-91ab-a8571a1384fb.png">

**Comment by abolabo** [comment]
cke replaced by tinymce

**Comment by BasaraABC** [comment]
Looks like editor replacement is buggy.

1. On fresh install when you login to dashboard admin the Settings Wizard start but then white screen appear, firebug report error "ReferenceError: tinymce is not defined"
<img width="977" alt="mozilla_firefox" src="https://cloud.githubusercontent.com/assets/2631910/12711005/7e776f06-c8ee-11e5-9f6c-be36b6edbf7d.png">

2. Also can you please check **original issue**? It is **not fixed**. 
<img width="687" alt="2016-02-01_14-38-27" src="https://cloud.githubusercontent.com/assets/2631910/12711390/12e35422-c8f2-11e5-8025-035361035595.png">

P.S 
Please do not close issues. I will re-check and close after fix

**Comment by abolabo** [comment]
fixed. now it stores new line breaker and tabs

**Comment by BasaraABC** [comment]
Issue not fixed. Editor still modify code
<img width="734" alt="2016-02-04_19-04-31" src="https://cloud.githubusercontent.com/assets/2631910/12814594/cac71826-cb72-11e5-8e34-cde966f72b5e.png">

**Comment by abantecart** [comment]
Is this still valid?

**Comment by BasaraABC** [comment]
yes it is valid. Visual editor add/remove tags

**Comment by abantecart** [comment]
First, original code is incorrect, that is why editor auto-corrects. 
Same will be if you will have open <a> and no losing. It will close. 
I think it is OK behavior. 

http://archive.tinymce.com/wiki.php/Configuration3x:cleanup

All 3 settings are set to false. 

I do not think we can do anything here.
