### ISSUE TITLE
dev issue: favicon error on fresh install

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#327]
<img width="917" alt="favicon" src="https://cloud.githubusercontent.com/assets/2631910/12258132/d7e3e9d0-b93e-11e5-8dc1-b10ee8b781cb.png">

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Issue not fixed. Fresh install
<img width="743" alt="products" src="https://cloud.githubusercontent.com/assets/2631910/12711444/8a51ee60-c8f2-11e5-935c-2b6bf951032e.png">

**Comment by abolabo** [comment]
fixed (on admin-side)

**Comment by BasaraABC** [comment]
The warning is gone but issue is still there. When you visit appearance section in admin the Favicon is visible but is Not saved. Please see screenshot
<img width="886" alt="template_manager" src="https://cloud.githubusercontent.com/assets/2631910/12741107/358a2ae0-c9ac-11e5-8626-3cc0ea398d44.png">

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Issue come back again. If system check is ON on fresh install error in messages 
<img width="928" alt="message_manager" src="https://cloud.githubusercontent.com/assets/2631910/13518503/2d314c6c-e201-11e5-9214-68d78e587706.png">

**Comment by abolabo** [comment]
fixed
