### ISSUE TITLE
dev issue: Send mail to guest customers ordered not work

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#346]
if select product the customer purchased it - did not receive email
<img width="968" alt="2016-02-05_18-01-21" src="https://cloud.githubusercontent.com/assets/2631910/12844725/c50e26ec-cc33-11e5-967b-d2e9a3cfae2b.png">

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Issue is not fixed. See screenshot
<img width="1025" alt="2016-02-26_20-28-04" src="https://cloud.githubusercontent.com/assets/2631910/13353577/ee82f954-dcc7-11e5-8141-4844d7bc5ef0.png">

**Comment by abolabo** [comment]
cannot to replicate. All works correctly. if you have no orders with product it will show that you have no recipients for your email.

**Comment by BasaraABC** [comment]
I found where is problem. Send Mail doesnot send mail to Guest customers. To replicate create order with Guest checkout

**Comment by BasaraABC** [comment]
Can not check fixes. Critical error `load error: AbanteCart core v.1.2.9 Error: Could not load model sale_order from /abc129_m12d06/admin/model/sale/contact.php on line 209 in /abc129_m12d06/core/engine/loader.php</b> on line <b>109</b>`
