### ISSUE TITLE
dev issue: Visual editor problem

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#350]
Visual editor works unexpected. It add nttttttt text and broke a lot of html tags.
To replicate try html attached in archive
<img width="699" alt="2016-02-08_14-30-50" src="https://cloud.githubusercontent.com/assets/2631910/12880224/ec8438d0-ce70-11e5-8fe6-6da3813a48a7.png">

I suggest to disable in editor feature to add/remove anything

[index.html.zip](https://github.com/abantecart/abantecart-src/files/121243/index.html.zip)

**Comment by abantecart** [comment]
Dima, check the code that you created for preserving format. It needs to be more stable and preserve text format 100%

**Comment by abantecart** [comment]
Possibly we need to disable HTML formatting in timymc completely

**Comment by abantecart** [comment]
Fixed. Note, large HTML will take some time to switch between tabs. This depends on your computer power. 
I tried to add loader and it did not work. This is rare condition.

**Comment by BasaraABC** [comment]
Initial issue is not fixed: still ntttttttt text added.
<img width="968" alt="new_text_compare__-_text_compare" src="https://cloud.githubusercontent.com/assets/2631910/13419128/6b370588-dfae-11e5-9945-eed605e91bff.png">

______________________________________________________________________________
Issue B: editor add not necessary tags
<img width="837" alt="2016-03-01_12-58-51" src="https://cloud.githubusercontent.com/assets/2631910/13419038/c4b41ea8-dfad-11e5-8f2a-ea5d9c409acf.png">

**Comment by abantecart** [comment]
Fixed. 

NOTE: Doctype, head and other conflicting tags will not be supported by visual editor. 
Full page mode that I enabled before cause other issues with showing doctype and head.

We should be done here.
