### ISSUE TITLE
dev issue: RL UI

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#360]
<img width="1178" alt="products" src="https://cloud.githubusercontent.com/assets/2631910/12913835/959030b8-cf53-11e5-87d3-d2186c8a0da9.png">

**Comment by abantecart** [comment]
Fixed.

**Comment by BasaraABC** [comment]
Both issues not fixed. 
Please fix at least  Issue B: I suggest to remove 'link' button in right panel near 'Linked To' text
<img width="1156" alt="products" src="https://cloud.githubusercontent.com/assets/2631910/12940935/498c7fe8-d000-11e5-9176-1b6aba579e63.png">

**Comment by abantecart** [comment]
I fixed the alignment of button on the side. Let and right buttons are different. I do not see big issue here. 

Thank you
