### ISSUE TITLE
dev: new text editor remove scrollbar in IE 11

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#376]
![img_11022016_152128](https://cloud.githubusercontent.com/assets/2631910/12971953/529ed422-d0d3-11e5-8952-1fc89b7539c7.png)

**Comment by abantecart** [comment]
Fixed

**Comment by BasaraABC** [comment]
Issue not fixed. In IE11 visible on mouseover and in other browsers see screen
![img_17022016_202422](https://cloud.githubusercontent.com/assets/2631910/13110810/cb477ff6-d5b4-11e5-9fb5-042f41195ea9.png)

**Comment by abantecart** [comment]
Created one more solution. Try now.

**Comment by abantecart** [comment]
I close it, so you see it.
