### ISSUE TITLE
dev issue: RL manager broken listing

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#379]
Listing is broken see screenshot. In my opinion related to different resources.  As seen on screenshot boxes height is different
<img width="1170" alt="media_resource_library_manager" src="https://cloud.githubusercontent.com/assets/2631910/12974000/44638046-d0e3-11e5-88a4-0aa7249fc40c.png">

**Comment by abantecart** [comment]
I believe, I fixed it.

**Comment by BasaraABC** [comment]
Issue is not fixed. Visible in fresh install FF and Chrome. Go to Common media library (rt=tool/rl_manager) and add  these images
[testimages.zip](https://github.com/abantecart/abantecart-src/files/133751/testimages.zip)

**Comment by BasaraABC** [comment]
Looks like FireFox browser glitch. Issue closed
