### ISSUE TITLE
dev issue: IM settings ui

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#402]
By default all communication extensions are not installed. It is not clear for user that you need to install/enable and configure this extensions. Please add help note to the System > Settings> IM page and if possible open in new window communication extension page when it selected in the Provider dropdown
<img width="856" alt="2016-02-22_15-05-24" src="https://cloud.githubusercontent.com/assets/2631910/13212705/e5c2495a-d975-11e5-91ab-b7017f5659e4.png">

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
You forgot to add help note for _SMS Provider_ field about provider extension installation to be available in this list

**Comment by abolabo** [comment]
added
