### ISSUE TITLE
dev issue: paypal/twillio, SSL and multistore

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#432]
test setup have 2 stores: default - ssl off, and second - ssl ON. When test twillio in default store the "loading" never completed and SSL related error in log
<img width="1154" alt="2016-02-25_12-26-30" src="https://cloud.githubusercontent.com/assets/2631910/13311046/d8f1d0de-dbbd-11e5-9c88-89a82dab243f.png">

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Multistore related issue still here. Test use incorrect credentias
<img width="1074" alt="2016-02-29_20-07-16" src="https://cloud.githubusercontent.com/assets/2631910/13395427/35d306cc-df21-11e5-8f2f-e12d94fc4d11.png">

**Comment by abolabo** [comment]
fixed. 
changes affected twilio, textmarketer, pp_pro, pp_express, fedex (only test credential functionality on settings page).

**Comment by BasaraABC** [comment]
Twillio and Texmarketer test buttons works but in Paypal Pro I get error for the default store
" Connection to PayPal server can not be established. error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure. Check your server configuration or contact your hosting provider. "

Please note SSL in OFF for default store and On for second store.

**Comment by abolabo** [comment]
SSL setting for AbanteCart does not affect to connections with paypal api server. 
You should to note what protocol (http or https) do you use on your admin side.
Problem handshake failure means that you have misconfigured ssl on your web-server and paypal api server does not allows to connect with it (for ex self-signed certificate cause). i tested this situation on your testcase and see that ssl-error shows on both stores.

**Comment by abolabo** [comment]
SSL setting for AbanteCart does not affect to connections with paypal api server. 
You should to note what protocol (http or https) do you use on your admin side.
Problem handshake failure means that you have misconfigured ssl on your web-server and paypal api server does not allows to connect with it (for ex self-signed certificate cause). i tested this situation on your testcase and see that ssl-error shows on both stores.
