### ISSUE TITLE
System > Settings > All settings issues

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#450]
## Issue A: many settings are not editable see screenshots
<img width="937" alt="2016-02-26_20-34-27" src="https://cloud.githubusercontent.com/assets/2631910/13353681/88194b72-dcc8-11e5-8e89-d3fd462082c0.png">

<img width="928" alt="2016-02-26_20-37-21" src="https://cloud.githubusercontent.com/assets/2631910/13353745/e4eca2c2-dcc8-11e5-8f65-0d3bb8d9e4c8.png">
___________________________________________________
## Issue B: a lot of missed settings in grid
For example I can not find new settings in the All settings Tab: recaptcha, order cancellation etc even by key (config_customer_cancelation_order_status, config_recaptcha_site_key)

**Comment by abolabo** [comment]
some settings was absent in db after install. just added empty values.
fixed

**Comment by BasaraABC** [comment]
**encryption_key** settings still not editable. Also new settings you add is not editable too (try **config_customer_cancelation_order_status_id**). Please check you fixes.
<img width="931" alt="settings" src="https://cloud.githubusercontent.com/assets/2631910/13386721/20b312bc-dee2-11e5-8181-2b6e76881c3e.png">

**Comment by abolabo** [comment]
fixed. encryption_key will not show now(we have no UI for this setting)
