### ISSUE TITLE
dev issue: mobile dropdown and Z-index SF

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#482]
z-index probem with new mobile dropdown (Chrome, FireFox)
<img width="709" alt="create_account" src="https://cloud.githubusercontent.com/assets/2631910/13593865/e68b6bd8-e531-11e5-97e3-a84f61deb054.png">

**Comment by abantecart** [comment]
What browser is this?

**Comment by BasaraABC** [comment]
Chrome and FireFox

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Issue not fixed on SF. When create account it is missed and error in firebug
`TypeError: $(...).intlTelInput is not a function
	$('#AccountFrm_sms').intlTelInput({`

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Could you please also fix this problem in Embed SF.

**Comment by abolabo** [comment]
fixed
