### ISSUE TITLE
large blurb in listings

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#487]
Note: to replicate issue please add large blurbs to 4-5 products because bug not visible all the time
<img width="1241" alt="2016-03-09_13-12-53" src="https://cloud.githubusercontent.com/assets/2631910/13627044/05ff999e-e5fa-11e5-8c52-08526a66626d.png">

**Comment by abantecart** [comment]
Fixed. Found better solution for listing. Please check in browsers and include embed.

**Comment by BasaraABC** [comment]
Listing is broken see screenshot
<img width="657" alt="your_store" src="https://cloud.githubusercontent.com/assets/2631910/13660708/17f38d7a-e6bf-11e5-9de4-9d9a6fb02ea8.png">

**Comment by abantecart** [comment]
Fixed

**Comment by BasaraABC** [comment]
Issue not fully fixed and visible in fresh install in Chrome, FireFox, Safari 9 browsers
<img width="626" alt="my_store_title" src="https://cloud.githubusercontent.com/assets/2631910/13694098/71486f10-e784-11e5-82ff-f9c3b35876fb.png">

**Comment by abolabo** [comment]
ignore this line. Pavel made it
