### ISSUE TITLE
google analytics - Ecommerce tracking improve

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#528]
Looks like the google analytics is outdated. Please check
<img width="1368" alt="ga" src="https://cloud.githubusercontent.com/assets/2631910/14734156/c376a8f4-0892-11e6-9d6b-063dbe74c6ea.png">

**Comment by abolabo** [comment]
Our code in google-analytics is OK

**Comment by abantecart** [comment]
We have specific code to track ecommerce. This will require detailed review. Le's push to next release

**Comment by BasaraABC** [comment]
Issue valid with Ecommerce tracking

**Comment by abantecart** [comment]
Fixed. Please test.

**Comment by BasaraABC** [comment]
Ecommerce tracking is work only partly. 

1. Product's quantity, product revenue , name are not tracked (GA > Conversion > Ecommerce > **Sales Performance** > click to  view Transaction Details )
2. Product List Performance is not work - no data in GA > Conversion > Ecommerce >  **Product List Performance**

**Comment by BasaraABC** [comment]
Most of the data are work now. Thank you.
However improvements needed - some data still missing:
     * product brand (Conversions > Ecommerce > Overview > Product Brand)
     * Product List Performance (Conversions > Ecommerce > Product List Performance)

**Comment by abolabo** [comment]
Boris, where is screenshots? i don't see in my acc all that you wrote

**Comment by BasaraABC** [comment]
I will recheck again

**Comment by BasaraABC** [comment]
Dont work in 2.0.0.a 
checked after a day, real time working but Ecommerce is not work. Please debug

**Comment by BasaraABC** [comment]
Update: Ecommerce work in Overview only
Like mentioned before other data is not working. For example coupons, product brands, listing views/clicks etc
Please see screenshot proofs
![2017-03-23_14-41-11](https://cloud.githubusercontent.com/assets/2631910/24237388/a3bbae1c-0fd8-11e7-99bf-53aa71a84637.png)

**Comment by BasaraABC** [comment]
Pro features may effecting performance. Moved to 2.0
