### ISSUE TITLE
dev: HTTPS to HTTP

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#601]
problem with changing back to HTTP for pages where SSL is not required. How to replicate
1.Visit HTTP home page
2. then click on login link it will direct you to the HTTP**S** secure page (do not login).
3. then click on Store logo in header. Issue: you will be redirected to the HTTP**S** home page.

**Comment by abantecart** [comment]
This is addressed. We need to do a good testing

**Comment by BasaraABC** [comment]
Issue is not fixed. Logo return https url if visit secure page

**Comment by BasaraABC** [comment]
One more problem: https url to home page in breadcrumb. Note - visible in downloads page
<img width="572" alt="2016-08-10_17-07-55" src="https://cloud.githubusercontent.com/assets/2631910/17550185/f03ad8d8-5f1d-11e6-9add-2c8832163aa0.png">

**Comment by abantecart** [comment]
Fixed.
