### ISSUE TITLE
dev: HTTPS and Embed

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#604]
If change all src in the embed code to http**s** then mixed content loaded 
see http://embedac.blogspot.com/2016/07/https.html
<img width="609" alt="2016-07-11_16-33-13" src="https://cloud.githubusercontent.com/assets/2631910/16726213/48fe2fe8-4785-11e6-9b26-f59102d19245.png">

**Comment by abolabo** [comment]
fixed. do not forget clear cache before testing!

**Comment by BasaraABC** [comment]
issue is not fixed. (browser cache was cleared)
<img width="585" alt="2016-07-22_17-23-07" src="https://cloud.githubusercontent.com/assets/2631910/17054409/38219c78-5031-11e6-9e08-e443c4f8c174.png">
