### ISSUE TITLE
rounding issue

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#685]
To replicate use same demo product in Euro and set Per Item shipping $10.00
<img width="707" alt="2016-10-03_16-45-19" src="https://cloud.githubusercontent.com/assets/2631910/19033520/0074aa90-8989-11e6-92e3-7241f90b6697.png">

**Comment by kolynet** [comment]
this is  a big leak on my live environment, can you guys help in a quick manual fix? spent days trying to fix.

**Comment by abantecart** [comment]
Can you share the details? You can email access to your site to help@abantecart.com and reference this issue #685

**Comment by kolynet** [comment]
i sent an email. confirm if you have received!

**Comment by abantecart** [comment]
I see your email. Thank you

**Comment by kolynet** [comment]
were you able to replicate the issue?

**Comment by abantecart** [comment]
This issue is fixed. Fix is not with a best approach, but it is due to a global effect on totals use. This will be considered to be changed in future on major release

**Comment by kolynet** [comment]
Can I please know the workaround? Very appreciate your work and time. 
But i would need to make the changes. You could just send me the 
affected files if its easier!


Thanks!


-

**Comment by kolynet** [comment]
something still not ok. when you change currency form the default currency on store and using combined mlutiple products, try to end ur total with odd, or even number, and you will notice that paypal will throw express checkout because the difference. if you add each product one by one, it will be €0.01 different from the subtotal/total.

**Comment by abantecart** [comment]
The fix was exactly for what you explain.  Are you sure you applied all the fixes/files?

**Comment by kolynet** [comment]
yeah surely! try using default currency USD, use EUR with 0.89 conversion rate or something, put in some products into cart, try to mix as much as possible and you will see that the total will not be same if you manually add product on cart.

**Comment by kolynet** [comment]
but i can make a test abantecart on my host, email you the access, if it helps!

**Comment by abantecart** [comment]
I tested express checkout on my test and it builds correctly rounded values. Please email how we can check your specific case. Please include FTP and admin access.

**Comment by kolynet** [comment]
sending in email now

**Comment by abantecart** [comment]
Thank you for participating in the fix. I have found one more case of penny loss in currency conversion in subtotal. Fixed now.

**Comment by kolynet** [comment]
thanks, awesome!

**Comment by kolynet** [comment]
there is still an issue while changing currency and product price is odd '16.67' and you put a quantity of '3' for example. seems like currency exchange with multiple quantity issue happens rarely. backend calculated with 3 decimal and round up, while the exchanged currency count 2 decimal and cause 1 penny difference which throw paypal express error again. might be something in /core/lib/currency.php couldnt figure out yet.

**Comment by abantecart** [comment]
I am working on this now

**Comment by abantecart** [comment]
It turned out much more to this issue. Check out commit above. There are few files affected.

**Comment by abantecart** [comment]
Need to QA.
