### ISSUE TITLE
tasks: backup - ui issues when compress fail

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#710]
When task fail to compress backup folder :
Issue A: no message about failed compress step - it actually fail
Issue B: step 4 shown as success undefined
<img width="1234" alt="2016-11-14_17-30-51" src="https://cloud.githubusercontent.com/assets/2631910/20261540/c8075c06-aa90-11e6-81f9-d2fa0ba6586c.png">
Note: to simulate compress fail - put few large 33MB files into root folder.

**Comment by abolabo** [comment]
needs to details to replicate. probably fixed by other commit

**Comment by abantecart** [comment]
Probably is not god. We need to confirm 100%.

**Comment by BasaraABC** [comment]
Very easy to replicate see note in initial report (Note: to simulate compress fail - put few large 33MB files into root folder.).
Let me explain problem again: if for any reason backup compress fail the Step 4 should not say "Success" and _undefined_  text also should be replaced with some details

**Comment by abolabo** [comment]
fixed

**Comment by BasaraABC** [comment]
Issue is not fixed. I able to replicate it on my localhost (bitnami installation, fresh 129 install). When compression failed still have 'success...undefined' text and error in log see screenshot
<img width="964" alt="2016-11-23_17-01-10" src="https://cloud.githubusercontent.com/assets/2631910/20557628/cede60a0-b19e-11e6-82c6-c6cfccc02e99.png">

**Comment by BasaraABC** [comment]
Issue fixed for now. But please do not close it. I want to run few more tests
