### ISSUE TITLE
Maintenance Mode issues

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#893]
### Issue 1. It is not work in dev 1.2.11 
To replicate login to admin via https go to settings -> Enable Maintenance and click top right link to see storefront
See screenshot.
![2017-06-15_12-26-28](https://user-images.githubusercontent.com/2631910/27166720-e8a78a20-51c6-11e7-805b-7bd49cdfcdd2.png)

<hr>

### Issue 2: after session is end and admin relogin it also stop to work please see
http://forum.abantecart.com/index.php/topic,5735.0/topicseen.html

**Comment by abolabo** [comment]
move to 2.0

**Comment by abantecart** [comment]
Issue 1 is a bug.

**Comment by abolabo** [comment]
issue 1 was fixed in #839

**Comment by BasaraABC** [comment]
Both issues are not fixed. When session time is end admin see storefront as regular customer.

**Comment by abolabo** [comment]
Bug will be valid until old session cookie has been removed
