### ISSUE TITLE
dev: import wizard - image import title

### ISSUE THREAD

**Issue by BasaraABC** [abantecart/abantecart-src#958]
Please set product name as image's title when import or leave it empty. Now all imported images have title **1**
![2017-09-01_17-26-42](https://user-images.githubusercontent.com/2631910/29966166-d5d9cbcc-8f3a-11e7-91db-9100593d1c90.png)

**Comment by abantecart** [comment]
Done

**Comment by BasaraABC** [comment]
Issue is not fixed. See screenshot
![2017-09-06_13-26-46](https://user-images.githubusercontent.com/2631910/30097302-28cfbe34-9307-11e7-9b25-a9b424522d37.png)

**Comment by abantecart** [comment]
Missed little thing. Fixed now
